name: Build core linux_64

on: workflow_dispatch

jobs:
  build:
    name: Build core
    runs-on: linux_64
    container:
      image: ghcr.io/heatray/onlyoffice-builder:v1
      env:
        TZ: Etc/UTC
        # MAKEFLAGS: -e -j8 -O recurse

    steps:
      - name: Test
        run: |
          set -eux
          ls -la /
          ls -la /github
          ls -la /github/home
          ls -la /home
          ls -la /home/user
          printenv
      - name: Build
        run: |
          set -eux
          git clone https://github.com/ONLYOFFICE/build_tools.git ||:
          cd build_tools
          ./configure.py \
            --module "core" \
            --platform linux_64 \
            --update true \
            --clean true \
            --qt-dir $QT_PATH
          ./make.py
          ls -la out/linux_64/onlyoffice/core/
