name: Build online installer

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version'
        type: string
        # required: true
      build:
        description: 'Build number'
        type: string
        # required: true
      sign:
        description: 'Sign installer'
        type: boolean
        default: true

jobs:
  build:
    name: Build online installer
    runs-on: [ self-hosted, Windows, onlineinstaller ]
    steps:

    - name: Checkout
      run: |
        $repos = "build_tools", "core", "desktop-apps"
        $repos | % {
          if (-not (Test-Path $_)) {
            ni -ItemType Directory -Force -Path $_
          }
          pushd $_
          if (-not (Test-Path .git)) {
            git clone --depth 1 git@git.onlyoffice.com:ONLYOFFICE/$_.git .
          }
          else {
            git fetch --depth 1
            git reset --hard origin/master
          }
          popd
        }

        $repo = "desktop-onlineinstaller"
        if (-not (Test-Path $repo)) {
          ni -ItemType Directory -Force -Path $repo
        }
        pushd $repo
        if (-not (Test-Path .git)) {
          git clone git@git.onlyoffice.com:ONLYOFFICE/$repo.git .
        }
        else {
          git reset --hard origin/master
        }
        popd

    - name: Build
      run: |
        sl desktop-onlineinstaller

        (Get-Content -Path make.py) -replace "build_sln", "qmake" | Set-Content -Path make.py
        (Get-Content -Path make.py) -replace "__dir__name__ \+ '/sln.json'", "'win_32_xp','OnlineInstaller.pro'" | Set-Content -Path make.py

        write "::group::Config"
        $env:QT_PATH = C:\Qt\5.6.3
        write "module=onlineinstaller
        branch=master
        platform=win_32_xp
        config=release
        clean=0
        update=0
        qt-dir=`"$env:QT_PATH`"
        qt-dir-xp=`"$env:QT_PATH`"" > config
        gc config
        write "::endgroup::"

        write "::group::Build"
        $PSNativeCommandUseErrorActionPreference = $True
        python make.py
        write "::endgroup::"

    - name: Archive artifact
      uses: actions/upload-artifact@v4
      with:
        name: onlineinstaller
        path: desktop-onlineinstaller/build/win_32/online-installer.exe
        if-no-files-found: error
