name: Build online installer

on: workflow_dispatch

jobs:
  build:
    name: Build online installer
    runs-on: windows-2019
    steps:

    - name: Install Qt
      uses: jurplel/install-qt-action@v4
      with:
        version: 5.15.2
        target: desktop
        arch: win32_msvc2019
        # arch: 'win64_msvc2019_64'
        use-official: true
        email: ${{ secrets.QT_EMAIL }}
        pw: ${{ secrets.QT_PW }}
        cache: true
        cache-key-prefix: install-qt-action

    - name: Build
      run: |
        $ErrorActionPreference = "Stop"

        git clone https://github.com/ONLYOFFICE/build_tools.git
        git clone https://github.com/ONLYOFFICE/desktop-onlineinstaller.git

        $env:QT_PATH = "$env:QT_ROOT_DIR\..\.." | Resolve-Path
        $env:QT_PATH
        $env:QT_ROOT_DIR

        sl desktop-onlineinstaller

        echo "module=onlineinstaller" >> config
        echo "branch=master" >> config
        echo "platform=win_32" >> config
        echo "config=release" >> config
        echo "clean=0" >> config
        echo "update=0" >> config
        echo "update-light=0" >> config
        echo "git-protocol=https" >> config
        echo "vs-version=2019" >> config
        echo "qt-dir=`"$env:QT_PATH`"" >> config
        echo "qt-dir-xp=`"$env:QT_PATH`"" >> config
        gc config
        python make.py

        gci
