name: Example self-hosted

on: workflow_dispatch

jobs:
  compile:
    name: Test
    runs-on: self-hosted
    steps:
      - name: Test
        run: |
          set -eux
          printenv
          echo "test${{ github.run_number }}" >> test.txt
          cat test.txt
          echo "CONTEXT GITHUB"
          echo "${{ toJson(github) }}"
          echo ${{ github.ref_name }}
          echo ${{ github.base_ref }}
          echo ${{ github.head_ref }}
