name: Example self-hosted

on: workflow_dispatch

jobs:
  compile:
    name: Test
    runs-on: self-hosted
    steps:
      - name: Test
        run: |
          set -eux
          ls -la
          echo "test${{ github.run_number }}" >> test.txt
          cat test.txt
          echo "CONTEXT GITHUB"
          echo "${{ github }}"
          echo "CONTEXT ENV"
          echo "${{ env }}"
          echo "CONTEXT VARS"
          echo "${{ vars }}"
          echo "CONTEXT INPUTS"
          echo "${{ inputs }}"
