name: Build core linux_64 (github-hosted)

on: workflow_dispatch

jobs:
  build:
    name: Build core
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/heatray/onlyoffice-builder:v4

    steps:
      - name: Build
        run: |
          set -eux
          git clone https://github.com/ONLYOFFICE/build_tools.git ||:
          cd build_tools
          ./configure.py \
            --module "core" \
            --platform linux_64 \
            --update true \
            --clean true \
            --qt-dir $QT_PATH
          ./make.py
          ls -la out/linux_64/onlyoffice/core/
