name: Build online installer

on: workflow_dispatch

jobs:
  build:
    name: Build online installer
    runs-on: windows-2019
    steps:

    - name: Install Qt
      uses: jurplel/install-qt-action@v4
      with:
        version: 5.15.2
        target: desktop
        arch: win32_msvc2019
        # arch: 'win64_msvc2019_64'
        use-official: true
        email: ${{ secrets.QT_EMAIL }}
        pw: ${{ secrets.QT_PW }}
        cache: true
        cache-key-prefix: install-qt-action

    - name: Build
      run: |
        write "[ Clone ]"
        git clone -q https://github.com/ONLYOFFICE/build_tools.git
        git clone -q https://github.com/ONLYOFFICE/core.git
        git clone -q https://github.com/ONLYOFFICE/desktop-apps.git
        git clone -q https://github.com/ONLYOFFICE/desktop-onlineinstaller.git

        sl desktop-onlineinstaller

        (Get-Content -Path make.py) -replace "build_sln", "qmake" | Set-Content -Path make.py
        (Get-Content -Path make.py) -replace "__dir__name__ \+ '/sln.json'", "'win_32','OnlineInstaller.pro'" | Set-Content -Path make.py

        gc make.py

        write "[ Config ]"
        $env:QT_PATH = "$env:QT_ROOT_DIR\.." | Resolve-Path
        write "module=onlineinstaller
        branch=master
        platform=win_32
        config=release
        clean=0
        update=0
        update-light=0
        vs-version=2019
        qt-dir=`"$env:QT_PATH`"" >> config
        gc config

        write "[ Build ]"
        $PSNativeCommandUseErrorActionPreference = True
        python make.py
        # if ($LastExitCode -ne 0) { throw }

        gci
        gci build\win_32

    - name: Archive artifact
      uses: actions/upload-artifact@v4
      with:
        name: onlineinstaller
        path: desktop-onlineinstaller/build/win_32/online-installer.exe
        if-no-files-found: error
        compression-level: 0
