name: Example

on: workflow_dispatch

jobs:
  compile:
    name: Compile core
    runs-on: ubuntu-latest
    container:
      image: ubuntu:16.04
      env:
        TZ: Etc/UTC
        # UNAME: user
        # UID: 1000
        # GID: 1000
      # volumes:
      #   - my_docker_volume:/volume_mount

    steps:
      - name: Prepare
        run: |
          set -eux

          apt-get -y update
          apt-get -y install \
              python \
              python3 \
              sudo \
              git
          ln -sf /usr/bin/python2 /usr/bin/python

          # groupadd -g $GID $UNAME
          # useradd -m -u $UID -g $GID -s /bin/bash $UNAME

      - name: Compile
        run: |
          set -eux

          mkdir -p /workspace
          cd /workspace

          git clone --depth 1 https://github.com/ONLYOFFICE/build_tools.git
          cd build_tools

          ./configure.py \
            --module "core" \
            --platform linux_64 \
            --update true \
            --clean true
          ./make.py
