name: Markdown Lint

on:
  workflow_dispatch:
  push:
    branches:
      - '**'
    paths:
      - '*.md'
      - 'develop/*.md'

jobs:
  markdownlint:
    runs-on: ubuntu-latest
    steps:
      - run: |
          printenv
          cat << EOF
          ${{ toJson(github) }}
          EOF
