name: Markdown Lint & Spellcheck

on:
  workflow_dispatch:
  push:
    branches:
      - '**'
    paths:
      - 'CHANGELOG.md'
      - '.aspell.*.pws'

jobs:
  markdownlint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: DavidAnson/markdownlint-cli2-action@v16
        with:
          # config: '.markdownlint.jsonc'
          globs: |
            CHANGELOG.md
  spellcheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup aspell
        run: |
          sudo apt-get -y update
          sudo apt-get -y install aspell aspell-en
      - name: Run spellchecker
        run: |
          while read line; do
            echo $line
            code=1
          done < <(cat CHANGELOG.md \
            | aspell --encoding=utf-8 \
              --mode=markdown \
              --lang=en \
              --personal=./.aspell.en.pws \
              list \
            | sort -u)
          exit ${code:-0}
