name: Markdown check

on:
  workflow_dispatch:
  push:
    paths:
      - '*.md'
      - 'develop/*.md'

jobs:
  markdownlint:
    runs-on: ubuntu-latest
    steps:
      - run: |
          printenv
          echo "${{ github.ref }}"
