name: Docker testing

on:
  workflow_dispatch:
    inputs:
      release:
        type: choice
        description: Release branch
        options:
          - testing
          - unstable
      version:
        description: 'Version (ex. 1.2.3)'
        type: string
        # required: true
      build:
        description: 'Build (ex. 45)'
        type: string
        # required: true
      amd64:
        type: boolean
        description: 'Build AMD64'
        default: true
      arm64:
        type: boolean
        description: 'Build ARM64'
        default: true
      community:
        type: boolean
        description: 'Build Community Edition'
        default: true
      enterprise:
        type: boolean
        description: 'Build Enterprise Edition'
        default: true
      developer:
        type: boolean
        description: 'Build Developer Edition'
        default: true

env: 
  COMPANY_NAME: "onlyoffice"
  PRODUCT_NAME: "documentserver"
      
jobs:
  prepare:
    runs-on: ubuntu-latest
    outputs:
      platforms: ${{ steps.prepare.outputs.platforms }}
      editions: ${{ steps.prepare.outputs.editions }}
    steps:
      - id: matrix
        run: |
          set -eux

          [ ${{ github.event.inputs.amd64 }} = true ] && PLATFORMS+=("amd64")
          [ ${{ github.event.inputs.arm64 }} = true ] && PLATFORMS+=("arm64")
          if [ -z "${PLATFORMS[*]}" ]; then
            echo "None of the platforms are selected."
            exit 1
          fi
          json_platforms=$(jq -n -c --arg arr "${PLATFORMS[*]}" '($arr|split(" "))')
          echo "::set-output name=platforms::$json_platforms"

          [ ${{ github.event.inputs.community }} = true ] && EDITIONS+=("community")
          [ ${{ github.event.inputs.enterprise }} = true ] && EDITIONS+=("enterprise")
          [ ${{ github.event.inputs.developer }} = true ] && EDITIONS+=("developer")
          if [ -z "${EDITIONS[*]}" ]; then
            echo "None of the editions are selected."
            exit 1
          fi
          json_editions=$(jq -n -c --arg arr "${EDITIONS[*]}" '($arr|split(" "))')
          echo "::set-output name=editions::$json_editions"

  build:
    name: "Build DocumentServer ${{ matrix.edition }}"
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        image: ["documentserver"]
        edition: ${{fromJson(needs.prepare.outputs.editions)}}
    steps:
      - name: Checkout code 
        uses: actions/checkout@v3

      # - name: Set up QEMU
      #   uses: docker/setup-qemu-action@v2

      # - name: Set up Docker Buildx
      #   id: buildx
      #   uses: docker/setup-buildx-action@v2
     
      # - name: Login to Docker Hub
      #   uses: docker/login-action@v2
      #   with:
      #     username: ${{ secrets.DOCKER_HUB_USERNAME }}
      #     password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Debug
        run: |
          echo ${{ github.event.inputs.release }}
          echo ${{ github.event.inputs.version }}
          echo ${{ github.event.inputs.build }}
          printenv

      - name: Get Tag Name
        run: |
          echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

      - name: Build 4testing
        run: |
          set -eux

          ### ==>> At this step build variable declaration ###
          DOCKER_TAG=$( echo ${{ env.RELEASE_VERSION }} | sed 's/^v//' )
          PACKAGE_VERSION=$( echo $DOCKER_TAG | sed -E 's/(.*)\./\1-/' )
          RELEASE_BRANCH=${{ github.event.inputs.release }}

          PLATFORMS=("linux/amd64" "linux/arm64")

          ### ==>> Build and push images at this step ###

          [ "${{ matrix.edition }}" == "community"  ] && PRODUCT_EDITION=""
          [ "${{ matrix.edition }}" == "enterprise" ] && PRODUCT_EDITION="-ee"
          [ "${{ matrix.edition }}" == "developer"  ] && PRODUCT_EDITION="-de"

          export PRODUCT_EDITION
          export PACKAGE_URL=http://repo-doc-onlyoffice-com.s3.amazonaws.com/${COMPANY_NAME}/${RELEASE_BRANCH}/ubuntu/${PACKAGE_NAME}_${PACKAGE_VERSION}_TARGETARCH.deb
          export DOCKERFILE=Dockerfile
          export PREFIX_NAME=4testing-
          export TAG=$DOCKER_TAG
          export PLATFORM=$(echo ${PLATFORMS[@]} | sed 's/ /,/g')
          export RELEASE_BRANCH
          echo \
          docker buildx bake -f docker-bake.hcl ${{ matrix.image }} --push
          echo "DONE: Build success >> exit with 0"
          exit 0
        shell: bash
