name: Docker testing
run-name: >
  Build #${{ inputs.build }} [
  ${{ format('["{0}","{1}"]', inputs.amd64 && 'AMD64' || '', inputs.arm64 && 'ARM64' || '') }}
  ] [
  ${{ inputs.community && 'CE' || '' }}
  ${{ inputs.enterprise && 'EE' || '' }}
  ${{ inputs.developer && 'DE' || '' }}
  ]

on:
  workflow_dispatch:
    inputs:
      build:
        description: 'Build number (ex. 45)'
        type: string
        required: true
        default: 0
      amd64:
        type: boolean
        description: 'Build AMD64'
        default: true
      arm64:
        type: boolean
        description: 'Build ARM64'
        default: true
      community:
        type: boolean
        description: 'Build Community Edition'
        default: true
      enterprise:
        type: boolean
        description: 'Build Enterprise Edition'
        default: true
      developer:
        type: boolean
        description: 'Build Developer Edition'
        default: true

env:
  COMPANY_NAME: "onlyoffice"
  PRODUCT_NAME: "documentserver"

jobs:
  prepare:
    runs-on: ubuntu-latest
    steps:
      - name: Set global vars
        run: |
          echo "BUILD_NUMBER=${{ inputs.build }}" >> $GITHUB_ENV

      - id: matrix
        run: |
          set -ex

          BRANCH_NAME=${GITHUB_REF#refs/heads/}

          [ ${{ inputs.amd64 }} = true ] && PLATFORMS+=("amd64")
          [ ${{ inputs.arm64 }} = true ] && PLATFORMS+=("arm64")
          if [ -z ${PLATFORMS} ]; then
            echo "None of the platforms are selected."
            exit 1
          fi

          [ ${{ inputs.community }} = true ] && EDITIONS+=("community")
          [ ${{ inputs.enterprise }} = true ] && EDITIONS+=("enterprise")
          [ ${{ inputs.developer }} = true ] && EDITIONS+=("developer")
          if [ -z ${EDITIONS} ]; then
            echo "None of the editions are selected."
            exit 1
          fi
