name: Initialize changelog files

on: workflow_dispatch

jobs:
  changelog:
    if: >-
      ${{ contains(github.ref, 'refs/heads/hotfix/v') ||
          contains(github.ref, 'refs/heads/release/v') }}
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.PUSH_TOKEN }}

      - name: Set version
        run: |
          REF="${{ github.ref }}"
          echo "VERSION=${REF#*/v}" >> $GITHUB_ENV

      - name: Create changelog
        run: |
          CHANGES_DIR=win-linux/package/windows/update/changes/$VERSION
          mkdir -p $CHANGES_DIR

          declare -A HTML_WIN=(
            [en]="changes.html"
            [ru]="changes_ru.html")
          declare -A HTML_MAC=(
            [en]="ReleaseNotes.html"
            [ru]="ReleaseNotesRU.html")
          declare -A TITLE_WIN=(
            [en]="ONLYOFFICE Desktop Editors Release Notes"
            [ru]="История изменений ONLYOFFICE Desktop Editors")
          declare -A TITLE_MAC=(
            [en]="ONLYOFFICE Release Notes"
            [ru]="История изменений ONLYOFFICE")
          declare -A NEW_FEATURES=(
            [en]="New Features"
            [ru]="Новые функции")
          declare -A FIXES=(
            [en]="Fixes"
            [ru]="Исправления")
          declare -A EDITOR_ALL=(
            [en]="All Editors"
            [ru]="Все редакторы")
          declare -A EDITOR_DOCUMENT=(
            [en]="Document Editor"
            [ru]="Редактор документов")
          declare -A EDITOR_SPREADSHEET=(
            [en]="Spreadsheet Editor"
            [ru]="Редактор таблиц")
          declare -A EDITOR_PRESENTATION=(
            [en]="Presentation Editor"
            [ru]="Редактор презентаций")
          declare -A MORE=(
            [en]="and a little more..."
            [ru]="и прочее...")

          for lang in "en" "ru"; do
          cat > $CHANGES_DIR/${HTML_WIN["$lang"]} << EOF
          <!DOCTYPE html>
          <html>
          <head>
              <meta charset="utf-8">
              <title>${TITLE_WIN["$lang"]}</title>
              <style type="text/css">
                  body {
                      background: white;
                      font: 12px "Lucida Grande", "Lucida Sans Unicode", Verdana, Lucida, Helvetica, sans-serif;
                  }
                  h1, h2, h3 {
                      color: #000000;
                      font-family: "Helvetica";
                      font-weight: normal;
                      font-style: normal;
                  }
                  h1 {
                      font-size: 18px;
                  }
                  h2 {
                      font-size: 16px;
                  }
                  h3 {
                      font-size: 14px;
                  }
                  a {
                      text-decoration: none;
                  }
                  .releasedate {
                      color: #888;
                      font-size: medium;
                  }
                  .more {
                      margin-bottom: 20px;
                  }
              </style>
          </head>
          <body>
              <div class="version">
                  <h1>ONLYOFFICE Desktop Editors ${VERSION}<span class="releasedate"> - [[DATE]]</span></h1>

                  <h2>${NEW_FEATURES["$lang"]}</h2>
                  <h4>${EDITOR_ALL["$lang"]}</h4>
                  <ul>
                      <li>TODO</li>
                  </ul>
                  <h4>${EDITOR_DOCUMENT["$lang"]}</h4>
                  <ul>
                      <li>TODO</li>
                  </ul>
                  <h4>${EDITOR_SPREADSHEET["$lang"]}</h4>
                  <ul>
                      <li>TODO</li>
                  </ul>
                  <h4>${EDITOR_PRESENTATION["$lang"]}</h4>
                  <ul>
                      <li>TODO</li>
                  </ul>

                  <h2>${FIXES["$lang"]}</h2>
                  <h4>${EDITOR_ALL["$lang"]}</h4>
                  <ul>
                      <li>TODO</li>
                  </ul>
                  <h4>${EDITOR_DOCUMENT["$lang"]}</h4>
                  <ul>
                      <li>TODO</li>
                  </ul>
                  <h4>${EDITOR_SPREADSHEET["$lang"]}</h4>
                  <ul>
                      <li>TODO</li>
                  </ul>
                  <h4>${EDITOR_PRESENTATION["$lang"]}</h4>
                  <ul>
                      <li>TODO</li>
                  </ul>

                  <div class="more"><a href="https://github.com/ONLYOFFICE/DesktopEditors/blob/master/CHANGELOG.md#${VERSION//./}" target="_blank">${MORE["$lang"]}</a></div>
              </div>
          </body>
          </html>
          EOF
          done

          CHANGES_DIR=macos/ONLYOFFICE/update/updates/ONLYOFFICE/changes/$VERSION
          mkdir -p $CHANGES_DIR

          for lang in "en" "ru"; do
          cat > $CHANGES_DIR/${HTML_MAC["$lang"]} << EOF
          <!DOCTYPE html>
          <html>
          <head>
              <meta charset="utf-8">
              <title>${TITLE_MAC["$lang"]}</title>
              <style type="text/css">
                  /* variables */
                  :root {
                      --color-black: #141923;
                      --color-white: #fff;
                      --color-gray-100: #f7fafc;
                      --color-gray-200: #edf2f7;
                      --color-gray-300: #e2e8f0;
                      --color-gray-400: #cbd5e0;
                      --color-gray-500: #a0aec0;
                      --color-gray-600: #718096;
                      --color-gray-700: #4a5568;
                      --color-gray-800: #2d3748;
                      --color-gray-900: #1a202c;
                  }
                  body {
                      background: var(--color-white);
                      color: var(--color-gray-800);
                      font: 12px "Lucida Grande", "Lucida Sans Unicode", Verdana, Lucida, Helvetica, sans-serif;
                  }
                  h1, h2, h3 {
                      color: var(--color-gray-800);
                      font-weight: normal;
                      font-style: normal;
                  }
                  h1 {
                      font-size: 1.7em;
                  }
                  h2 {
                      font-size: 1.4em;
                      font-weight: lighter;
                  }
                  h4 {
                      font-size: 1.2em;
                      font-weight: lighter;
                  }
                  code {
                      background: var(--color-gray-200);
                      font-family: monospace;
                      padding: 1px 5px;
                  }
                  ul {
                      padding: 0 0 0 20px;
                  }
                  li {
                      margin-left: 20px;
                      margin-bottom: 0.2em;
                      padding: 0;
                  }
                  hr {
                      margin: 20px 0;
                      border: var(--color-gray-400) solid 0.5px;
                  }
                  .releasedate {
                      color: var(--color-gray-600);
                      font-weight: lighter;
                  }

                  /* prefers light mode */
                  @media (prefers-color-scheme: dark) {
                      body {
                          background: var(--color-gray-900);
                          color: var(--color-gray-200);
                      }

                      h1, h2, h3 {
                          color: var(--color-white);
                      }

                      code {
                          background: var(--color-gray-800);
                          color: var(--color-gray-200);
                      }

                      .releasedate {
                          color: var(--color-gray-600);
                      }
                  }
              </style>
          </head>
          <body>
              <div class="version">
                  <h1>ONLYOFFICE ${VERSION}<span class="releasedate"> - [[DATE]]</span></h1>

                  <h2>${NEW_FEATURES["$lang"]}</h2>
                  <h4>${EDITOR_ALL["$lang"]}</h4>
                  <ul>
                      <li>TODO</li>
                  </ul>
                  <h4>${EDITOR_DOCUMENT["$lang"]}</h4>
                  <ul>
                      <li>TODO</li>
                  </ul>
                  <h4>${EDITOR_SPREADSHEET["$lang"]}</h4>
                  <ul>
                      <li>TODO</li>
                  </ul>
                  <h4>${EDITOR_PRESENTATION["$lang"]}</h4>
                  <ul>
                      <li>TODO</li>
                  </ul>

                  <h2>${FIXES["$lang"]}</h2>
                  <h4>${EDITOR_ALL["$lang"]}</h4>
                  <ul>
                      <li>TODO</li>
                  </ul>
                  <h4>${EDITOR_DOCUMENT["$lang"]}</h4>
                  <ul>
                      <li>TODO</li>
                  </ul>
                  <h4>${EDITOR_SPREADSHEET["$lang"]}</h4>
                  <ul>
                      <li>TODO</li>
                  </ul>
                  <h4>${EDITOR_PRESENTATION["$lang"]}</h4>
                  <ul>
                      <li>TODO</li>
                  </ul>
              </div>
          </body>
          </html>
          EOF
          done

      - name: Commit changes
        uses: EndBug/add-and-commit@v9
        with:
          author_name: github-actions[bot]
          author_email: github-actions[bot]@users.noreply.github.com
          message: Initialize changelogs for v${{ env.VERSION }}
