name: GitHub Actions Demo
on: delete
jobs:
  jenkins-remote-job:
    runs-on: ubuntu-latest
    steps:
    - run: echo "Clean up for branch ${{ github.event.ref }}"
    - name: curl
      uses: wei/curl@v1
      with:
        args:
          - "-L"
          - "ident.me"
