name: Update hard-coded version
on: create
jobs:
  update-version:
    if: ${{ startsWith(github.event.ref, 'hotfix/') || startsWith(github.event.ref, 'release/') }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.4.0
      - run: |
          date > generated.txt
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "generated"
          git push
