name: Release online installer

on:
  workflow_dispatch:

jobs:
  build:
    name: Release online installer
    runs-on: ubuntu-latest
    steps:

    - name: Download artifacts
      env:
        GH_TOKEN: ${{ github.token }}
      run: |
        set -x
        # VERSION=${{ github.ref_name }}
        VERSION=v1.1.8.64
        VERSION=${VERSION#v}
        echo "VERSION=$VERSION" >> $GITHUB_ENV

        gh run download \
          --repo ${{ github.repository }} \
          --name OnlineInstaller-1.1.8-64

        ls -la
        which aws

    # - name: Download artifacts
    #   uses: actions/download-artifact@v5
    #   with:
    #     name: OnlineInstaller-1.1.8-64
    #     # pattern: OnlineInstaller-*
    #     run-id: 16054279714
