name: Release online installer

on:
  workflow_dispatch:

jobs:
  build:
    name: Release online installer
    runs-on: ubuntu-latest
    steps:

    - name: Set Variables
      run: |
        set -x
        PACKAGE=OnlineInstaller
        echo "PACKAGE=$PACKAGE" >> $GITHUB_ENV
        # VERSION=${{ github.ref_name }}
        VERSION=v1.1.8.64
        VERSION=${VERSION#v}
        echo "VERSION=$VERSION" >> $GITHUB_ENV

    - name: Download artifact
      id: download-artifact
      uses: dawidd6/action-download-artifact@v11
      with:
        workflow: build-online-installer.yml
        run_number: 64
        # skip_unpack: false

    # - name: Download artifacts
    #   uses: actions/download-artifact@v5
    #   with:
    #     name: OnlineInstaller-1.1.8-64
    #     github-token: ${{ github.token }}
    #     run-id:

    - name: Test
      run: |
        ls -la
