name: Release online installer

on:
  workflow_dispatch:

jobs:
  build:
    name: Release online installer
    runs-on: ubuntu-latest
    steps:

    - name: Set Variables
      run: |
        set -x
        temp=v1.1.8.64
        echo "\
        PACKAGE=ONLYOFFICEDesktopInstaller
        VERSION=${temp#v}
        RUN_NUMBER=${temp##*.}\
        " >> $GITHUB_ENV

    - name: Download artifact
      id: download-artifact
      uses: dawidd6/action-download-artifact@v11
      with:
        workflow: build-online-installer.yml
        name: OnlineInstaller-1.1.8-64
        run_number: ${{ env.RUN_NUMBER }}

    - name: Test
      run: |
        ls -la
